# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 8081


# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["LibPro/LibPro.csproj", "LibPro/"]
COPY ["LibraryApplication/LibraryApplication.csproj", "LibraryApplication/"]
COPY ["LibraryDomain/LibraryDomain.csproj", "LibraryDomain/"]
COPY ["LibraryInfrastructure/LibraryInfrastructure.csproj", "LibraryInfrastructure/"]
RUN dotnet restore "./LibPro/LibPro.csproj"
COPY . .
WORKDIR "/src/LibPro"
RUN dotnet build "./LibPro.csproj" -c $BUILD_CONFIGURATION -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./LibPro.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
RUN mkdir -p /app/assets/covers && chown -R $APP_UID /app/assets
USER $APP_UID
ENTRYPOINT ["dotnet", "LibPro.dll"]
